### ISSUE TITLE
Error on /vote command in RocketChat 0.74.3

### ISSUE THREAD

**Issue by MikeViento** [sampaiodiego/rocket.chat.app-poll#16] opened 2019-04-28 09:39 UTC
In RocketChat v. 0.74.2 works fine, but in v. 0.74.3 returns in logs this error:
`[
  "Error voting: ",
  "{\"stack\":\"Error: Meteor.userId can only be invoked in method calls or publications.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:93:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:298:32)
    at Messages.cloneAndSaveAsHistoryById (packages/rocketchat:models/server/models/Messages.js:373:39)
    at EventEmitter.RocketChat.updateMessage (packages/rocketchat:lib/server/functions/updateMessage.js:28:30)
    at Promise.asyncApply (packages/rocketchat:apps/server/bridges/messages.js:41:14)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Meteor.userId can only be invoked in method calls or publications.\"}"
]`
I think, it's a problem inside RocketChat app-engine, but how can i fix this?

**Comment by sampaiodiego** [comment] 2019-04-29 12:34
this is probably a duplicate of https://github.com/sampaiodiego/rocket.chat.app-poll/issues/14

in that case the error was related to the setting `Keep Per Message Editing History` see https://github.com/sampaiodiego/rocket.chat.app-poll/issues/14#issuecomment-482672986

the fix is included in latest rocket.chat version (see [1.0.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/1.0.0) and [1.0.1](https://github.com/RocketChat/Rocket.Chat/releases/tag/1.0.1))

**Closed by sampaiodiego** 2019-04-29 12:34 UTC
