### ISSUE TITLE
Does not work on mobile app

### ISSUE THREAD

**Issue by BigMayo** [sampaiodiego/rocket.chat.app-poll#18] opened 2019-05-31 16:24 UTC
Can see a posted poll, but can not respond to poll from mobile app.
Selection box appears to not be drawn correctly.

Also, can not create a new poll from mobile app.
Does not error, just does not do anything.

**Comment by sampaiodiego** [comment] 2019-05-31 17:13
The APIs used by Poll app are not fully compatible with Rocket.Chat Mobile Apps yet, I've created issues on mobile apps repos already as follow:
RocketChat/Rocket.Chat.iOS#2565
RocketChat/Rocket.Chat.Android#2036
RocketChat/Rocket.Chat.ReactNative#649

I'll be closing this issue as duplicate of https://github.com/sampaiodiego/rocket.chat.app-poll/issues/11

**Closed by sampaiodiego** 2019-05-31 17:13 UTC
